
version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: